- name: Ensure basic packages
  yum:
    name:
      - wget
      - tar
      - firewalld
    state: present

- name: Disable firewalld (SG already protects host)
  service:
    name: firewalld
    state: stopped
    enabled: no

