- name: restart prometheus
  systemd:
    name: prometheus
    daemon_reload: yes
    state: restarted

- name: restart node_exporter
  systemd:
    name: node_exporter
    daemon_reload: yes
    state: restarted
