- name: restart prometheus
  systemd:
    name: prometheus
    daemon_reload: yes
    state: restarted

- name: restart node_exporter
  systemd:
    name: node_exporter
    daemon_reload: yes
    state: restarted

- name: reload systemd
  command: systemctl daemon-reload

- name: restart cloudwatch exporter
  systemd:
    name: cloudwatch_exporter
    state: restarted
    enabled: yes

- name: restart loki
  systemd:
    name: loki
    state: restarted
    daemon_reload: yes
